# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1cdaccbb54829deb4298edba6eb64d2d0dc11045e93c750abf65bac14da0ead48c9f38b959003aaa92818fd6117a86acae85270fa6124f537246c6cfd4269f78

test:
  secret_key_base: 169146d7268541bcefdc4eab133d2a6e48a684e858d77a5318c76f8e6a01ffb2a7f8a2e09622bc08a1155f01b311589982262f5e4418b9dca9b90ca1c6c87a89

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
